[package]
name = "sdrscanner"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
rtlsdr = { path = "../rtlsdr-rs" }
rustfft = "6.4.0"
sdr = {path = "../libsdr"}
smoothed_z_score = "0.1.3"
tokio = { version = "1.46.1", features = ["full"] }
