[package]
name = "sdrscanner"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.29.0"
rtlsdr = "0.1.4"
rustfft = "6.4.0"
rustradio = "0.14.2"
sdr = {path = "../libsdr"}
smoothed_z_score = "0.1.3"
tokio = { version = "1.46.1", features = ["full"] }
rust-dsdcc = {path = "../rust-dsdcc"}

[profile.release]
opt_level = 3
lto = true
